### ISSUE TITLE
Some charachters in passwords may break rtsp request URLs

### ISSUE THREAD

**Issue by abelykh** [bluecherrydvr/bluecherry-client#107]
Some chars such as ":", "@", etc may break the rtsp URLs making the live view feeds to go to into "error".

**Comment by antonsviridenko** [comment]
Tested now with user "specialchar@@@"  and password ":::" on v2demo. Actually live view works well, but client fails to get events, 

```
EventData::parseEvents error: "Invalid feed format"
```
is printed in console

**Comment by antonsviridenko** [comment]
server returns 
```
<script>window.location = "/";</script>
```
instead of valid events XML

**Comment by antonsviridenko** [comment]
previous message was caused by lack of "Backup access" privilege for user

everything works fine with special chars in username and password, not a bug, closing
