### ISSUE TITLE
Recorded videos on Linux Mint only show 1/4 corner of video, live view works fine

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-client#133]
gstreamer issue?

![screen shot 2013-06-10 at 11 10 13 am](https://f.cloud.github.com/assets/331478/632863/f4d66a6c-d1ed-11e2-82c4-95b00f4db2c0.png)

**Comment by antonsviridenko** [comment]
gstreamer is replaced by mplayer, bug is not relevant anymore
