### ISSUE TITLE
Auto-connecting to local bc-server

### ISSUE THREAD

**Issue by krieger-od** [bluecherrydvr/bluecherry-client#213]
When bc-client is run first time, and there is a bc-server running on localhost, it automatically opens local server. But after a restart, it cannot connect to it, pretending it is a host with empty hostname. Looks the config file is generated incorrectly.

**Comment by antonsviridenko** [comment]
Unable to reproduce with current client, possibly fixed in https://github.com/bluecherrydvr/bluecherry-client/commit/a33c306d209dbac598150563539a10bd8c517f5d
