### ISSUE TITLE
Aspect ratio problems

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-client#241]
http://community.bluecherrydvr.com/topic/please-provide-the-ability-to-lock-the-aspect-ratio-of-live-video-feeds-in-the-client-application

**Comment by curtishall** [comment]
http://community.bluecherrydvr.com/topic/preserve-aspect-ratio-in-client-separate-the-view-and-event-windows

**Comment by antonsviridenko** [comment]
Resizing of original frame size without keeping aspect ratio happens somewhere here in
LiveStreamItem::paint()
https://github.com/bluecherrydvr/bluecherry-client/blob/master/src/ui/liveview/LiveStreamItem.cpp#L125
