### ISSUE TITLE
Temporary files not deleted

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-client#246]
As reported:

https://secure.helpscout.net/conversation/151336575/7515/

I am using Windows client 2.2.2 and over time, I found my disk space was steadily decreasing on my hard disk. I poked around, and I see that the bluecherry client dumps temporary files into %temp% (for me it was C:\Users\bvrielin\AppData\Local\Temp) when the video data is being transferred from the server to the client. Example file names of temporary files:

bc_vbuf_em4664.mkv
bc_vbuf_gq4664.mkv
bc_vbuf_q11956.mkv

They don't ever seem to be deleted. It would be good if the client deleted these when it was done with them. By deleting them I managed to recover 64GB of hard disk space.

**Comment by antonsviridenko** [comment]
Files can be deleted on closing event player, closing client or client startup, maybe all 3 conditions can be used. I think that its better to delete temp files on all platforms, not only Windows. tmp directories are usually cleaned on system startup

**Comment by antonsviridenko** [comment]
Temporary video files are deleted in normal conditions, but sometimes they can be left when client is terminated (in situations like client crash, killed from Task Manager, computer poweroff, etc).

I've added code that cleans temp files by pattern "bc_vbuf_*.mkv" on bluecherry client startup.
https://github.com/bluecherrydvr/bluecherry-client/commit/636dab71ff35a62214bf1dc3949d75a6bae74af4
