### ISSUE TITLE
Incorrect Video Playback speed.

### ISSUE THREAD

**Issue by masterspline** [bluecherrydvr/bluecherry-client#254]
The playback always plays at about 2x. Changing playback speed doesn't work at all.

http://community.bluecherrydvr.com/topic/linux-video-playback-speed-problem

**Comment by masterspline** [comment]
The reason is in mplayer. To solve it I need to use latest (1.3.0) mplayer regardless of Linux distro.

**Comment by antonsviridenko** [comment]
Did you test recording file with other players? Maybe recording is damaged/corrupted

**Comment by masterspline** [comment]
I did not, but guy from http://community.bluecherrydvr.com/topic/linux-video-playback-speed-problem did.

**Comment by masterspline** [comment]
Pawel said, in mplayer 1.3 (now blucherry client has mplayer in package) playback speed is ok.
http://community.bluecherrydvr.com/topic/linux-video-playback-speed-problem
