### ISSUE TITLE
Screen Saver configuration creates big delays in client start and work on Ubuntu.

### ISSUE THREAD

**Issue by masterspline** [bluecherrydvr/bluecherry-client#261]
On Ubuntu (not Kubuntu or other spinoff) bluecherry client starts with big delay about 25 seconds (lagging) with enabled ScreenSaver configuration (turn it off, when bc-client is working) and also delays on each video player start. More information:
https://secure.helpscout.net/conversation/192236350/8376/?folderId=795871
http://community.bluecherrydvr.com/topic/ubuntu-client-2-2-3-lags-to-open-frequent-lags-with-event-playback
And copy-past from public room in HipChat
# 

"@AlexeySyrnikov hey. Jason Sauders here. (the guy you were talking to with the laggy client start). I found something of interest.
￼
In settings >> General tab >> "Prevent computer from going to sleep when..." if I uncheck "Always prevent the computer from going to sleep" (the top option of the 3), the client opens just fine. Nearly instant.
￼
With only the top option unchecked, it makes the client open rather fast. _but_ if I play back events at the bottom of the live view screen, I still get random (and frequent) hangups for the 25 second pause before they start (such as what was in that dropbox video I sent you). If I uncheck _all 3_ options, that field operates just fine.
￼
So in short, it seems (so far) that if I uncheck all 3 of those options, things operate as normal. So it seems there's still a bug of some sort specifically when using Ubuntu Unity, but unchecking these options make the client far more responsive. At least from what I've seen so far in my limited testing.
￼
I figured I'd look in the system settings after I was grepping for certain key terms in the config files from the client source. I was searching for "screens" (you mentioned in the strace it was locking where it mentioned "ScreenS" (for screen saver), so I was searching for that in particular), and found this: bluecherry-client-master/debian/changelog:  \* Bug #59: Add an option to disable screensavers on Linux
￼
I think in order to go through the proper channels I'll write up a bug report on it to keep everything secluded there. I saw you here and wanted to mention that in case you were active.
￼
Anyway, hope you folks are having a great day. Let me know if I can help or test anything."
#

**Comment by antonsviridenko** [comment]
it's probably related to D-Bus, which is used for disabling screensaver. Probably d-bus service is not running or has some other issues

**Comment by antonsviridenko** [comment]
looks like Qt bundled with 2.2.3 Ubuntu packages was build with dbus support disabled
