### ISSUE TITLE
Unable to play events in progress

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-client#262]
Broken several releases ago in the library used to play events.

**Comment by antonsviridenko** [comment]
Do you mean continuous records?

**Comment by curtishall** [comment]
No, you can play an event that has already finished in the client, however you can not play an event that hasn't been closed yet.  This was caused by the switch to mplayer I believe.

**Comment by antonsviridenko** [comment]
> however you can not play an event that hasn't been closed yet. 

closed by server or not fully downloaded by client yet?
