### ISSUE TITLE
Load previous settings on client startup

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-client#267]
In the event of a crash or a shutdown, reload the previous settings in the client.  This includes if the customer selected low bandwidth mode, camera layouts and views and if a camera was open in a new window

**Comment by curtishall** [comment]
http://community.bluecherrydvr.com/topic/auto-start-at-boot-multi-window-support

**Comment by antonsviridenko** [comment]
Bluecherry client already behaves this way, except 
> and if a camera was open in a new window

**Comment by mikketeus** [comment]
What about starting up in fullscreen mode?

On Thu, Oct 13, 2016 at 10:38 AM, Anton Sviridenko <notifications@github.com

**Comment by AlexanderAgd** [comment]
New window layout  and geometry  restore implemented  in #268. In the options page added checkbox 'Restore previous session', so user can enable or disable this feature. Important step is create a new or select layout in a new open window, so its  configuration will be saved.

**Comment by antonsviridenko** [comment]
audio state should also be restored (if some live stream camera had audio enabled)

**Comment by AlexanderAgd** [comment]
Restore audio state done.

**Comment by antonsviridenko** [comment]
Window opened in fullscreen is not restored in foreground now, it is restored in background after startup, behind the main window. I think that window ordering should be also stored in config

**Comment by AlexanderAgd** [comment]
Implemented save & restore top level window.
