### ISSUE TITLE
Ubuntu 16.10 support

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-client#287]
Currently running the client (2.2.5) crashes during live view with reference to LIBAVCODEC_57:

http://community.bluecherrydvr.com/topic/client-2-2-5-crush

https://secure.helpscout.net/conversation/290147313/10704/

**Comment by AlexanderAgd** [comment]
Problem comes from wrong client linkage value.

**Comment by antonsviridenko** [comment]
Ubuntu 16.10 has the same major version of libavcodec in repository (57) as shipped by bluecherry-client-2.2.5 package, and system one has higher priority during dynamic linking

**Comment by antonsviridenko** [comment]
workaround - use chrpath program to change RPATH paths order in bluecherry-client binary
```
# apt-get install chrpath
# chrpath --replace "/usr/lib/bluecherry/client:/usr/lib/x86_64-linux-gnu" /usr/bin/bluecherry-client
```

**Comment by antonsviridenko** [comment]
TODO: change RPATH order in build scripts

**Comment by antonsviridenko** [comment]
Fixed in https://github.com/bluecherrydvr/bluecherry-client/commit/34d6245d12142a365b21c6757eb79c36b7436009

"/usr/lib/x86_64-linux-gnu" was added as the RPATH for Qt libraries
