### ISSUE TITLE
Playing audio in liveview consumes inadequate CPU power when PulseAudio is present

### ISSUE THREAD

**Issue by antonsviridenko** [bluecherrydvr/bluecherry-client#291]
See https://github.com/bluecherrydvr/bluecherry-client/issues/289

Not reproducible without PulseAudio, when audio is played directly to ALSA device

**Comment by AlexanderAgd** [comment]
Thanks to pointing to some configurations in a scripts, this issue fixed.

**Comment by antonsviridenko** [comment]
https://github.com/bluecherrydvr/bluecherry-client-scripts/commit/f2f255e7b26ddea076556dc1dded3c9999d4eeab
