### ISSUE TITLE
is there a way to build with QT5?

### ISSUE THREAD

**Issue by ohquait** [bluecherrydvr/bluecherry-client#307]
i can not build the modules, since qt5 installed
plan you a update to qt5?

**Comment by curtishall** [comment]
We plan to eventually look at upgrading to Qt 5, however at the moment that is not high of the list of client changes.  

You are welcome to submit a PR :)

**Comment by ohquait** [comment]
I'm not a coder, I can only pack what Coders produce.
so i will keep in patience
