### ISSUE TITLE
build failed on Ubuntu 1604, QT 5 environment 

### ISSUE THREAD

**Issue by hongson23** [bluecherrydvr/bluecherry-client#325]
Hello @antonsviridenko, @curtishall 

Thank you for your great project, 
I build successfully on commit: 2682a54409634cfc93cd3d18033f301caf7eb431 (Update readme.md) on QT4 environment 
but after commit merge QT5-porting 58f91a01d216e3285b4b26837583b91bd237a516 and the latest commit this project can not build on ubuntu 1604 with qt5 environment 
There are some errors:
![er1](https://user-images.githubusercontent.com/4011696/111935385-f2cbdf80-8af5-11eb-9600-1cbeacf130f4.PNG)
![er2](https://user-images.githubusercontent.com/4011696/111935387-f52e3980-8af5-11eb-913b-5881c2373ad4.PNG)
![er3](https://user-images.githubusercontent.com/4011696/111935389-f6f7fd00-8af5-11eb-808d-abb050beead3.PNG)
Could you please help me check these issues ?

**Comment by antonsviridenko** [comment]
@hongson23 current master branch is not buildable and usable with Qt5 yet, but I'm actively working on this task now, new client release that uses Qt5 should be ready soon, I hope in a few days

**Comment by hongson23** [comment]
thank you!
I am looking forward to hearing from you

**Comment by antonsviridenko** [comment]
@hongson23 Qt5 porting is still in progress, but you can already try to build latest commit from master branch

**Comment by antonsviridenko** [comment]
it's preferable to build and run on Ubuntu 20.04, as dependencies provided by 16.04 repository are bit old

**Comment by hongson23** [comment]
thanks,
I am going to create ubuntu20.04 to build this project

**Comment by hongson23** [comment]
hello @antonsviridenko 
Bluecherry-client build successfully on Ubuntu 20.04 environment. I hope all features will be comeback after few days, thank you for great upgrade!
It is better if you update "sources.cmake" file for build with cmake-tool, currently I am using Makefile.am 

![bluecherryapp](https://user-images.githubusercontent.com/4011696/112589294-6ee66000-8e33-11eb-9259-11aa35b13d7e.PNG)

**Comment by antonsviridenko** [comment]
@hongson23 new version is released
