### ISSUE TITLE
libva-drm1, libva-x11-1, libva1 not available in Ubuntu 18.04 (they've moved to libva2) 

### ISSUE THREAD

**Issue by begleysm** [bluecherrydvr/bluecherry-client#326]
The client download page at https://www.bluecherrydvr.com/downloads/ suggests that the DEB at http://downloads.bluecherrydvr.com/client/2.2.6/xenial/bluecherry-client_2.2.6-1_amd64.deb is suitable for Ubuntu 16.04 and newer.  However Ubuntu 18.04 has moved from libva1 to libva2 and libva1 is no longer available in the standard repos.

Would it be possible to get a version of the client compiled for labva-drm2, libva-x11-2, and libva2?

Thanks,
Sean

**Comment by curtishall** [comment]
Can you try this? - http://downloads.bluecherrydvr.com/client/2.2.7/bionic/bluecherry-client_2.2.7-1_amd64.deb

**Comment by begleysm** [comment]
@curtishall The ol' sneaky hidden newer version trick.  That works like a charm!  Thanks!

**Comment by curtishall** [comment]
Sorry, my bad.  I forgot we built 2.2.7 just for 18.04 :0

A new release should be coming out in the next month...once we finish the upgrade to Qt5.

**Comment by begleysm** [comment]
Very cool.  I'm not sure who is in control of the website but an update to the download page would be really great :)

**Comment by curtishall** [comment]
> Very cool. I'm not sure who is in control of the website but an update to the download page would be really great :)
👍 

I just fixed it :)

**Comment by begleysm** [comment]
You da man!
