### ISSUE TITLE
Build fails on manjaro QT5

### ISSUE THREAD

**Issue by budgie05** [bluecherrydvr/bluecherry-client#327]
/bluecherry-client/src/ui/liveview/LiveFeedItem.cpp:216:23: error: ‘scene’ was not declared in this scope
  216 |     QWidget *window = scene()->views().value(0);

  
/bluecherry-client/src/ui/liveview/LiveFeedItem.cpp:255:5: error: ‘QDeclarativeItem’ has not been declared
  255 |     QDeclarativeItem::mousePressEvent(event);
      |     ^~~~~~~~~~~~~~~~

/bluecherry-client/src/ui/liveview/LiveFeedItem.cpp:514:37: error: ‘class QQuickItem’ has no member named ‘scene’
  514 |         QGraphicsView *view = item->scene()->views().value(0);

/bluecherry-client/src/ui/liveview/LiveFeedItem.cpp:515:32: error: ‘class QQuickItem’ has no member named ‘scene’
  515 |         Q_ASSERT(view && item->scene()->views().size() == 1);
  
  /bluecherry-client/src/ui/liveview/LiveFeedItem.cpp:517:90: error: no matching function for call to ‘QQuickItem::mapToScene(int, qreal)’
  517 |             pos = view->mapToGlobal(view->mapFromScene(item->mapToScene(0, item->height())));

  
/bluecherry-client/src/ui/liveview/LiveFeedItem.cpp:557:62: error: cannot convert ‘QRectF’ to ‘const QPointF&’
  557 |         QRect itemScreenRect = view->mapFromScene(mapToScene(QRectF(0, 0, width(), height()))).boundingRect();
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              |
      |                                                              QRectF

**Comment by antonsviridenko** [comment]
Please wait for the next release, should be available soon.

**Comment by budgie05** [comment]
Thank you for your work antonsviridenko client now builds and runs after the latest commits
