### ISSUE TITLE
Missing drag&drop event for adding camera to LiveViewWindow layout in latest version(porting QT5)

### ISSUE THREAD

**Issue by hongson23** [bluecherrydvr/bluecherry-client#329]
Hello @antonsviridenko 
Thank you for your upgrade to QT5. I tested bluecherry-client and that worked well on Ubuntu and also Window 10 with QT5.
I investigated that you replaced QDeclarativeItem with QWidget so it is missing "dragEnterEvent", "dragMoveEvent" ... so user can not use drag and drop event to add camera,
So do you have any plan to update this functionality ?
I think adding camera to LiveViewWindow via drag&drop event which is more convenient for end user

Thank you so much!

**Comment by antonsviridenko** [comment]
@hongson23 
Yes, I forgot about this feature while porting :) Should be fixed in the next release.

**Comment by hongson23** [comment]
Thank you for your information!

**Comment by antonsviridenko** [comment]
hi @hongson23 
can you take a look at the latest commit and see if it works for you?

**Comment by hongson23** [comment]
Hello @antonsviridenko
Thank you so much!
I tested your new implementing so all main functions work well ! 
There are some minor bugs, i am going to capture and let you know

**Comment by curtishall** [comment]
Can you submit a pull request with your changes?

**Comment by trongthanhqvo** [comment]
Yes, I create a pull requests,
I hope you will review code.
Thanks @curtishall @antonsviridenko
