### ISSUE TITLE
Bluecherry Client 2.2.9 macOS won't open on Big Sur 

### ISSUE THREAD

**Issue by ronluna** [bluecherrydvr/bluecherry-client#338]
Unable to get Bluecherry Client 2.2.9 to launch on Big Sur (Intel or M1) .

Tried to launch from the terminal as well but same results.

```
ronluna@Rons-iMac-8 MacOS % ./bluecherry-client 
2  audio devices detected by SDL audio subsystem
AudioPlayer: setting sample format to  s16  channels:  2 sample rate:  44100
void UpdateChecker::performVersionCheck() Performing update check
void UpdateChecker::versionInfoReceived() Latest version info:  "2.2.6"
```

**Comment by ronluna** [comment]
Same outcome on Catalina.

**Comment by antonsviridenko** [comment]
@ronluna 
> (Intel or M1) .
Hi!
Can you confirm that it does not run on Intel x86 hardware?

About M1, it is a known issue, emulation does not work well for many programs, we are going to make a separate build for M1 CPUs

**Comment by curtishall** [comment]
@ronluna we are working on this issue today.

**Comment by ronluna** [comment]
I can confirm 2.2.9 does not run on Intel x86 Hardware. tested in many Intel based mac on different OSX versions and bluecherry 2.2.9 won't launch.

**Comment by curtishall** [comment]
Can you try this M1 build?  http://lizard.bluecherry.net/~curt/releases/osx/client/BluecherryClient_2.2.9_M1_macports.dmg

And this x86 build (may crash...) http://lizard.bluecherry.net/~curt/releases/osx/client/BluecherryClient.dmg

**Comment by ronluna** [comment]
Seems the x86 build was build with the incorrect target as one the BluecherryClient.dmg image is mounted OSX shows the typical cross

**Comment by ronluna** [comment]
Any update on this ?

**Comment by curtishall** [comment]
@ronluna Can you try this build?

http://lizard.bluecherry.net/~mvov/releases/macOS/BluecherryClient_2.2.9_macMini_BigSur_x86_build.dmg

**Comment by ronluna** [comment]
Just tested but no love....

I get the following:

![image](https://user-images.githubusercontent.com/9822111/141034413-6da815c5-ac2e-49a1-8c1b-646e7c579dd0.png)


The logs show:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Applications/BluecherryClient.app/Contents/MacOS/bluecherry-client ; exit;
Rons-MBP-4:~ ronluna$ /Applications/BluecherryClient.app/Contents/MacOS/bluecherry-client ; exit;
dyld: Library not loaded: /usr/local/Cellar/ffmpeg/4.4.1/lib/libavcodec.58.dylib
  Referenced from: /Applications/BluecherryClient.app/Contents/Frameworks/libavformat.58.dylib
  Reason: image not found
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...43 completed.

[Process completed]

ad when after updating to zsh it returned:

/Applications/BluecherryClient.app/Contents/MacOS/bluecherry-client ; exit;
dyld: Library not loaded: /usr/local/Cellar/ffmpeg/4.4.1/lib/libavcodec.58.dylib
  Referenced from: /Applications/BluecherryClient.app/Contents/Frameworks/libavformat.58.dylib
  Reason: image not found
zsh: abort      /Applications/BluecherryClient.app/Contents/MacOS/bluecherry-client
Saving session...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by curtishall** [comment]
Thanks, can you try this build?

http://lizard.bluecherry.net/~mvov/releases/macOS/BluecherryClient_2.2.9_macMini_BigSur_x86_build_211111.dmg

**Comment by ronluna** [comment]
Success!!!! It worked!
Although it needs minor adjustments for "Dark mode"

![image](https://user-images.githubusercontent.com/9822111/141395770-c40b9152-2dab-434a-9726-befb7f1a1fd8.png)

**Comment by curtishall** [comment]
Thanks....this has been pretty frustrating but glad we finally have it working for you.

We'll look at these two issues you reported
