### ISSUE TITLE
Client is making several requests to server for video file that is about to be started

### ISSUE THREAD

**Issue by vogel** [bluecherrydvr/bluecherry-client#88]
From application output after start of any video:

MediaDownload: launching new request after seek 
MediaDownload: launching new request after seek 
MediaDownload: launching new request after seek 
MediaDownload: launching new request after seek 
MediaDownload: launching new request after seek 

Only one request should be made.

**Comment by antonsviridenko** [comment]
not a bug, gstreamer-based player was starting to play before the file was fully downloaded, seeking to other place required new request
